# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.1.{build}



#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012



#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  -x64
  -x86



# build Configuration, i.e. Debug, Release, etc.
configuration: 
  -Release
  -Debug
# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  project: TestTravis\TestTravis.sln      # path to Visual Studio solution or project
  
  # MSBuild verbosity level
  verbosity: normal


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  
  # pushing a single file
  - path: test.zip



#---------------------------------#
#     deployment configuration    #
#---------------------------------#

