# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.2.{build}



#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012



#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x64
  - Win32

configuration:
  - Debug
  - Release
  
build:
  project: TestTravis\TestTravis.sln      # path to Visual Studio solution or project
  
  # MSBuild verbosity level
  verbosity: normal


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#


